version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - NEXTAUTH_SECRET=4d971f5fb46691d7de393b930300bff20df53e71910778df017ddbcd2d2571b9
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/rental_db
      - REDIS_URL=redis://redis:6379/0  # Connect backend to Redis
      - SECRET_KEY=4d971f5fb46691d7de393b930300bff20df53e71910778df017ddbcd2d2571b9
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"  # Optional: expose for local testing
volumes:
  postgres_data: